---
name: 📚 Documentation

on:  # yamllint disable-line rule:truthy
  merge_group:
  pull_request:

jobs:
  build-documentation:
    name: Build documentation
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the documentation
        run: make doc
